### ISSUE TITLE
What's plan for the next release of durabletask-js?

### ISSUE THREAD

**Issue by TonyPythoneer** [microsoft/durabletask-js#43]
Hi @kaibocai ,

There are recent patches for `durabletask-js`.
* #40 
* #41
* #42

Is there a release plan that they can apply for the workflow part of Dapr JS SDK?
Could I get some thoughts from you on this?

Thank you!

**Comment by famarting** [comment]
ping

**Comment by TonyPythoneer** [comment]
https://github.com/microsoft/durabletask-js/pull/42 is merged now
